### ISSUE TITLE
Kinematic Constraint

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/ManiSkill-Legacy#12]
Hi, is there a way to implement a "sticky gripper" in maniskill? i.e. create a kinematic constraint when making contacts? Thanks.

**Comment by harryzhangOG** [comment]
I think all I need to do is to create a fixed link between the target joint and the gripper finger?

**Comment by tongzhoumu** [comment]
Hi @harryzhangOG ,

I have not fully understood what you mean by "sticky gripper". Do you mean a magic gripper that automatically grasps the target when it contacts the target?

**Comment by harryzhangOG** [comment]
yes. basically it is a gripper that upon contacting the object, it creates a kinematic constraint that never lets go of the object (analogous to a suction gripper). The core question is how to create a fixed kinematic constraint between the gripper and the target. Thanks/

**Comment by tongzhoumu** [comment]
Hi @harryzhangOG ,

Yes, it is possible to build a "magic gripper". However, ManiSkill focuses on physics-rich manipulation and currently does not have plans to support magic grasping. If you would like to add such a gripper in our environments, it is recommended to ask questions in the [SAPIEN github repo](https://github.com/haosulab/SAPIEN), which is the backend of ManiSkill. Thanks!
