### ISSUE TITLE
Exact State of Environment in Demonstrations

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#14]
Do we know the exact state of the environment in these demonstrations (i.e. position / orientation of articulated object)? Can this environment state scene be loaded into the visualizer? Or do we simply know the level of the environment used in the demonstrations (https://github.com/haosulab/ManiSkill-Learn/issues/8)?

**Comment by tongzhoumu** [comment]
Duplicate of https://github.com/haosulab/ManiSkill-Learn/issues/15
