### ISSUE TITLE
About Operational Space

### ISSUE THREAD

**Issue by 1800012973** [haosulab/ManiSkill-Legacy#16]
Hello, I have some questions about the operational space and EndEffectorInterface.  
1.What is the meaning of 'qpos' in `EndEffectorInterface` and `OperationalSpaceControlInterface`? Meanwhile there is a difference when calculating qpos in these two functions:  `s = np.concatenate([np.zeros(3), s])  # append dummy base qpos` in `OperationalSpaceControlInterface`, and `s = np.concatenate([qpos_mobile_base, s])` in `EndEffectorInterface`, are these two 'qpos' different?
2. What is coordinates the pose and vel (i.e ee_pose) w.r.t? Is it the camera coordinates?

**Comment by tongzhoumu** [comment]
Hi @1800012973 

1. The 'q' in `qpos` refers to the generalized coordinates. In our setting, `qpos` represents the joint angles of a robot or an articulated object. The difference you mentioned is in a previous version, they should be consistent in the current version. (Though the previous version is also correct.)

2. If you are using [this example](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/utils/ee.py), it gives you the pose of ee in the world frame. In addition, the point clouds we provided are also in the world frame.

**Comment by 1800012973** [comment]
> Hi @1800012973
> 
> 1. The 'q' in `qpos` refers to the generalized coordinates. In our setting, `qpos` represents the joint angles of a robot or an articulated object. The difference you mentioned is in a previous version, they should be consistent in the current version. (Though the previous version is also correct.)
> 2. If you are using [this example](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/utils/ee.py), it gives you the pose of ee in the world frame. In addition, the point clouds we provided are also in the world frame.

Thanks. Besides, I print ee_pose and find it has 7 dimensions like `([-1.17186, -0.0928636, 0.428826], [0.502932, -0.453418, 0.546922, -0.492289])`, what's the formulation of the 7D ee_pose? Is it in se(3) so that I can directly get the relative transformation?

**Comment by tongzhoumu** [comment]
Hi @1800012973 

The pose is represented as `(position, quaternion)`, so 3+4=7 dim in total.

**Comment by 1800012973** [comment]
> Hi @1800012973
> 
> The pose is represented as `(position, quaternion)`, so 3+4=7 dim in total.

Thank you!
