### ISSUE TITLE
Motion Planning for OpenCabinetDoor

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#17]
The paper mentions that OpenCabinetDoor "is relatively easy to solve by traditional motion planning and control pipelines." Under what assumptions? Given the optimal grasp pose? Given a map of the environment?

**Comment by tongzhoumu** [comment]
Hi @arjung128 ,

Compared to PushChair and MoveBucket, OpenCabinetDoor/Drawer are relatively easy to solve by motion planning + control. In OpenCabinetDoor/Drawer, it is possible to design grasp poses by heuristic rules, and after grasping the handle, the robot can move accordingly to open the door/drawer. However, in PushChair and MoveBucket, we even do not know how to manipulate the object, where to grasp, and how to hold the object firmly. Therefore, we believe it takes much more effort to solve PushChair and MoveBucket by planning + control compared to the OpenCabientDoor/Drawer.

In addition, door opening has been studied by several robotics papers (e.g., [this](https://ieeexplore.ieee.org/document/5509556)), but pushing char and moving/lifting buckets are less studied.

**Comment by arjung128** [comment]
Thanks for your response. What kind of heuristic rules are you thinking of for designing the grasp pose? Are you assuming we know the 3D location of the handle? If so, is your idea to move the end-effector to be close to the 3D location of the handle, and then manually guess and check the controls until the grasping is successful? Such heuristics would have to be designed for each object instance separately, right?

None of the three environment modes provide direct information about the 3D location of the handle, correct? I am interested in testing this hypothesis, but because it is difficult to get the 3D location of the handle, I am not sure how this can be done. Any ideas?

**Comment by xuanlinli17** [comment]
You can obtain the location of handle using `pointcloud` mode, since handle points are labeled with handle segmentation mask (see [here](https://github.com/haosulab/ManiSkill#segmentation-masks) in readme). Note that all agent vector and point cloud observations are in world frame while the action space is ego-centric.

**Comment by arjung128** [comment]
I see, thank you. I noticed that the environment initialization calls `_find_handles_from_articulation`, which populates `self.grasp_pose`, where `grasp_pose['link_0']` has two Poses -- do these poses represent end-effector grasping poses for the robot? Also, what do the arrays in `self.handles_info` represent?

**Comment by tongzhoumu** [comment]
Hi @arjung128 ,

The `self.grasp_pose` are some heuristic grasp poses used to generate dense rewards. The `handles_info` is used to determine which links can be chosen as targets.

**Comment by arjung128** [comment]
Got it, thanks!
