### ISSUE TITLE
Loading other objects

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/ManiSkill-Legacy#18]
Hi, if we want to load other objects from the Partnet Mobility dataset which part of the code should we change? Thank you.

**Comment by tongzhoumu** [comment]
Hi @harryzhangOG ,

You can add new objects by modifying the object model yml files, e.g., [this](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/assets/config_files/chair_models.yml).

However, the other objects in the PartNet Mobility dataset are not processed and verified to support our tasks, so we do not guarantee they can be plugged into our tasks properly.
