### ISSUE TITLE
Runtime error: Vulkan is not initialized

### ISSUE THREAD

**Issue by shen-hhao** [haosulab/ManiSkill-Legacy#19]
I installed the ManiSkill environment on a new machine, but when I run basic_example.py there is the problem.
File /usr/share/vulkan/icd.d/nvidia_icd.json exists and 'VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json' is ensured

> Traceback (most recent call last):
>   File "/home/shenhao/ManiSkill/basic_example.py", line 7, in <module>
>     env = gym.make('MoveBucket-v0')
>   File "/home/shenhao/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
>     return registry.make(id, **kwargs)
>   File "/home/shenhao/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
>     env = spec.make(**kwargs)
>   File "/home/shenhao/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
>     env = cls(**_kwargs)
>   File "/home/shenhao/ManiSkill/mani_skill/env/move_bucket.py", line 17, in __init__
>     super().__init__(
>   File "/home/shenhao/ManiSkill/mani_skill/env/base_env.py", line 93, in __init__
>     obs = self.reset(level=0)
>   File "/home/shenhao/ManiSkill/mani_skill/env/move_bucket.py", line 26, in reset
>     super().reset(*args, **kwargs)
>   File "/home/shenhao/ManiSkill/mani_skill/env/base_env.py", line 168, in reset
>     self._setup_cameras()
>   File "/home/shenhao/ManiSkill/mani_skill/env/base_env.py", line 224, in _setup_cameras
>     camera = self._load_camera(cam_info)
>   File "/home/shenhao/ManiSkill/mani_skill/env/base_env.py", line 211, in _load_camera
>     camera = self._scene.add_mounted_camera(
> RuntimeError: Vulkan is not initialized
> Segmentation fault (core dumped)

**Comment by tongzhoumu** [comment]
Hi @shen-hhao ,

1. First make sure your Nvidia driver is correctly installed. You can check by `nvidia-smi` and `nvcc -V`
2. If your driver works well, then please check Vulkan by `vulkaninfo`.

**Comment by shen-hhao** [comment]
nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Mon_Oct_12_20:09:46_PDT_2020
> Cuda compilation tools, release 11.1, V11.1.105
> Build cuda_11.1.TC455_06.29190527_0

vulkaninfo

> ERROR: [Loader Message] Code 0 : libGLX_nvidia.so.0: cannot open shared object file: No such file or directory
> Cannot create Vulkan instance.
> This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
> /build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER

**Comment by tongzhoumu** [comment]
Hi @shen-hhao 

As shown by the output of `vulkaninfo`, it seems your Vulkan driver is not correctly installed. What is your NVIDIA driver version? 

Also, this command perhaps helps: `sudo apt-get install mesa-vulkan-drivers`

**Comment by shen-hhao** [comment]
NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4
`sudo apt-get install mesa-vulkan-drivers` does not work

**Comment by shen-hhao** [comment]
Problem solved by reinstall NVIDIA Driver with version 460. 
Guess vulkan is not compatible with NVIDIA Driver Version 470.
