### ISSUE TITLE
dependencies seem to be private

### ISSUE THREAD

**Issue by MartinBertran** [haosulab/ManiSkill-Legacy#2]
The Sapien-RL-Benchmark repo seems to be set to private. I cannot find a public version of this repo

https://github.com/haosulab/sapien-rl-benchmark.git

**Comment by xuanlinli17** [comment]
Sorry we meant "ManiSkill" instead of "sapien-rl-benchmark". "sapien-rl-benchmark" was the name of this repo when we were developing it. We have fixed the readme.
