### ISSUE TITLE
SRDF file for Sciurus A2_single robot

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#21]
Would it be possible to provide a SRDF file for the Sciurus A2_single robot?

Or is it possible to generate this somehow? Running `mplib.Planner()` generates a SRDF file, but this does not seem to be correct due to its shortness (relative to the provided `panda.srdf`) -- the following is what is contained in the generated `A2_single.srdf` file:

```
<?xml version="1.0" ?>
<robot name="A2_single">
    <disable_collisions link1="right_panda_link7" link2="right_panda_hand" reason="Default"/>
</robot>
```

**Comment by tongzhoumu** [comment]
Hi @arjung128 

We currently do not have the SRDF files of our robots. And `mplib` can run without SRDF (see [this](https://github.com/haosulab/MPlib/issues/2)). If you want to use `mplib` to generate SRDF and find it does not work as expected, please open an issue in `mplib` github repo.

**Comment by arjung128** [comment]
Got it, thanks!
