### ISSUE TITLE
Handle Information in State Mode

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#22]
When the environment is in state-mode for the OpenCabinetDrawer task, the 94-dim state vector does not contain the handle information, correct? So for two different cabinet instances, if they have the same pose (i.e. positions, orientations, velocities, etc.), their state vector will be the same (assuming their `self.target_indicator` is the same), right?

**Comment by tongzhoumu** [comment]
Hi @arjung128 

State-mode does not provide any information about handles. There is no canonical way to describe an arbitrary 3D shape by a low-dimensional vector.

**Comment by arjung128** [comment]
Thank you for your prompt response. Could this be why a single policy does not generalize well to a large number of objects (Table 5)? If the policy doesn't receive information about the handles, then for one object instance it can memorize the position of the handle, but because the state contains no information about which type of articulated object is being interacted with (the state is indistinguishable when given another object), it cannot do this for multiple objects?

**Comment by tongzhoumu** [comment]
Hi @arjung128 ,

Yes, we need additional information to distinguish the different objects when training in more than one environment.
As for the results shown in table 5, we append a one-hot vector (an indicator of the object) to the state before passing it to the NN.

**Comment by arjung128** [comment]
I see, thanks!
