### ISSUE TITLE
Identify initial grasping frame in demonstrations

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#23]
In a given demonstration trajectory (RGBD + access to state information), is it possible to identify the first frame in which the handle is grasped? I am finding this difficult to do for both the `OpenCabinetDoor` and `OpenCabinetDrawer` tasks. I would have expected the velocities of the two fingers to be an indicator of grasping, but finger velocities seem to change even when the robot is navigating to the object. Is the dense reward any indicator of this? Or is there an easier way to identify the initial grasping frame? 

Thanks!

**Comment by tongzhoumu** [comment]
Hi @arjung128 ,

Identifying the first frame of grasping is a little bit tricky. Currently, we do not have a function that is able to detect grasping robustly. But if you really want to get some relevant information from the environment, you may find this function useful: `env._scene.get_contacts()`.

**Comment by arjung128** [comment]
Thanks!
