### ISSUE TITLE
Convert robot qpos to robot joint positions

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#24]
Is there an easy way to get the robot's joint positions given the robot's qpos (i.e. the robot state from [here](https://github.com/haosulab/ManiSkill/wiki/Detailed-Explanation-of-The-Agent-State-Vector))?

Thanks!

**Comment by tongzhoumu** [comment]
Hi @arjung128 ,

Could you please clarify the "robot's joint positions"? In my understanding, the joint position is just qpos.

**Comment by arjung128** [comment]
Hi @tongzhoumu,

By robot joint position, I meant the xyz position of each joint. Apologies for the confusion.

**Comment by tongzhoumu** [comment]
Try this:
```python
env.agent.set_state({
    'base_pos': base_pos,
    'base_orientation': base_ori,
    'qpos': qpos, # you do not have to fill every key of this dict
})
for joint in env.agent.robot.get_active_joints():
    print(joint.name, ':', joint.get_global_pose())
```

**Comment by arjung128** [comment]
This is exactly what I needed, thank you so much!
