### ISSUE TITLE
y-coordinate bias in starting location of robot

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Legacy#25]
The starting location of the robot seems to be biased to be to the left of the articulated object, across many evaluation episodes:

```
import gym
import mani_skill.env
import numpy as np

env = gym.make('OpenCabinetDoor-v0')
# env = gym.make('OpenCabinetDoor_1028-v0')

env.set_env_mode(obs_mode='state', reward_type='sparse')
ys = []
for level_idx in range(0, 20):
    obs = env.reset(level=level_idx)
    x, y = env.agent.get_state(by_dict=True)['base_pos']
    ys.append(y)
print(np.mean(ys), np.median(ys))
env.close()
```

Using this, I get `0.6809838 0.6660824` for `env = gym.make('OpenCabinetDoor-v0')`, and `0.77759504 0.75745267` for `env = gym.make('OpenCabinetDoor_1028-v0')`. Is there any reason why the y-coordinate is quite positive in both cases (indicating that the robot starts to the left of the articulated object more often than the right), and not close to 0?

**Comment by tongzhoumu** [comment]
Yes, in the two cabinet tasks, we put the robot on the left of the cabinet. This is because our single-arm robot only has a right arm, so it will make the gripper closer to the cabinet. In this way, we make the task less challenging.

**Comment by arjung128** [comment]
I see, thanks!
