### ISSUE TITLE
Registration of competition

### ISSUE THREAD

**Issue by swords123** [haosulab/ManiSkill-Legacy#3]
I have filled out the manikill registration form a few days ago，but there is no reply.  When the registration can be confirmed?

**Comment by fbxiang** [comment]
It will be confirmed before submission opens (08/09). We are currently working on the submission system and once it is finished, we will send out the confirmation with further instructions.

**Comment by tongzhoumu** [comment]
We have sent out the confirmation emails. Thanks for supporting us!
