### ISSUE TITLE
rendering in VNC server

### ISSUE THREAD

**Issue by hskAlena** [haosulab/ManiSkill-Legacy#6]
Hello,

I'm trying to use 'viewer' for debugging, but when I uncomment `env.render('human')` in basic_example.py, I get `RuntimeError: vk::PhysicalDevice::getSurfaceFormatsKHR: ErrorInitializationFailed`  when I do this on VNC server. The viewer works well on a local machine. 

I guess the VNC server setting is not a problem since it can render other gym environments like 'Humanoid-v2'.

I installed vulkan-utils just in case, `sudo apt install vulkan-utils`.
But things didn't change.

How can I fix this?

**Comment by tongzhoumu** [comment]
Hi hskAlena, can you provide more information about how you set up your VNC server? As far as I know, some VNC do not support vulkan.

**Comment by hskAlena** [comment]
I am using a tigervnc server with xfce4 and a realvnc viewer. 
Also it's ubuntu 18.04!
```
sudo apt update
sudo apt install xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
sudo apt install tigervnc-standalone-server tigervnc-common
```

Thank you!

**Comment by tongzhoumu** [comment]
I guess `xfce4` does not support vulkan. There is an alternative solution.

- Install packages by ```sudo apt update && sudo apt upgrade && sudo apt-get install xserver-xorg-video-dummy && sudo apt-get install x11vnc net-tools && sudo apt install vulkan-utils```. 
- Run ```nvidia-xconfig``` to generate a X configuration file on /etc/X11/xorg.conf. You can modify /etc/X11/xorg.conf to change the screen size. See [here](http://cosmolinux.no-ip.org/raconetlinux2/dummy_radeon_nvidia.html) for examples.
- Create a dummy screen by ```sudo X :1 -config /etc/X11/xorg.conf```. You can choose other numbers for the screen id instead of ```:1```.
- In another terminal
  - Run ```export DISPLAY=:1```. I recommend you to add it into .bashrc.
  - [optional] Run ```vulkaninfo``` to check if Vulkan works well.
- You can now run ```x11vnc -display :1``` in another terminal to start a vncserver. 
- If you don't want to restart VNC everytime you exits VNC viewer, just use ```x11vnc -display :1 -forever``` 

Let me know whether this works for you.

**Comment by hskAlena** [comment]
Sadly, it doesn't work for me. I get black screen everytime I try.

I have searched a lot, and those are what I've found out so far. Please correct me if I have something wrong.

1. Changing 'tigervnc +xfce4' to 'tigervnc+ gnome flashback' didn't work with the vulkan thing. 
    So, I guess vulkan doesn't work with X desktop.
2. So I came back to x11vnc (which doesn't require X desktop according to wiki) and I've found out 
   `x11vnc -display :1 -auth guess` works, not `x11vnc -display :1`.  This is trivial tho.
3. I changed gdm3 to lightdm, following the direction from youtube. But nothing changed.
4. I connected the remote server with a physical display, since I saw black screen problem can be solved with HDMI dummy thing. However, it didn't work.

**Comment by hskAlena** [comment]
I finally found out that Vino vnc server works. 
Although it needs HDMI connection and seems to have weak security, it works. 
However, if you find x11vnc or other working, please let me know! 

Thank you! :)

**Comment by tongzhoumu** [comment]
Good to see you have found a solution!

BTW, vulkan does work with X desktop and this is how I visualize on a remote server. Did you test `vulkaninfo` in the X desktop you create?

**Comment by hskAlena** [comment]
Sadly `vulkaninfo` doesn't work.

It **works** on local machine with a monitor on, but doesn't work on X desktop.
The error message is 
`/build/vulkan-tools-136mCR/vulkan-tools-1.1.126.0+dfsg1/vulkaninfo/vulkaninfo.h:816: failed with ERROR_INITIALIZATION_FAILED`.

I've done the followings,
1. `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/nvidia_icd.json`  - didn't work
2. modifying `/lib/systemd/system/gdm3.service`  -  didn't work
```
[Service]
ExecStartPre=/usr/bin/xinit /usr/share/gdm/generate-config
```
3. `echo $XDG_SESSION_TYPE` prints out  `x11`.

So,,, I guess I'm gonna stick to Vino server, not X desktop, if any other easy solution doesn't come out. :')
