### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by ray8828** [haosulab/ManiSkill-Legacy#9]
Hi, thanks for sharing this great work!
I'm trying to run the `basic_example.py` after following the installation instructions provided in the readme on our slurm cluster. However, this line `env = gym.make('OpenCabinetDoor-v0')` cause a segmentation fault and the program crashed. Could you provide some potential tips to solve it?

cuda 10.1, nvidia 450.142, ubuntu 20, rtx-2080ti

Thanks

**Comment by tongzhoumu** [comment]
Hi @ray8828 ,

Can you share the error logs with us? In addition, have you tried running the example in your local machine?

**Comment by ray8828** [comment]
The script i'm running is:

```python
import gym
import mani_skill.env

print("start")
env = gym.make('OpenCabinetDoor-v0')
# full environment list can be found in available_environments.txt
print("debug")
env.set_env_mode(obs_mode='state', reward_type='sparse')
# obs_mode can be 'state', 'pointcloud' or 'rgbd'
# reward_type can be 'sparse' or 'dense'
print(env.observation_space) # this shows the structure of the observation, openai gym's format
print(env.action_space) # this shows the action space, openai gym's format

for level_idx in range(0, 5): # level_idx is a random seed
    obs = env.reset(level=level_idx)
    print('#### Level {:d}'.format(level_idx))
    for i_step in range(100000):
        # env.render('human') # a display is required to use this function, rendering will slower the running speed
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action) # take a random action
        print('{:d}: reward {:.4f}, done {}'.format(i_step, reward, done))
        if done:
            break
env.close()
print("finished")
```

And I'm running in the interactive session on slurm, the terminal output looks like this:

```shell
python basic_example.py
start
Segmentation fault (core dumped)
```

Thanks!

**Comment by ray8828** [comment]
Seems the seg fault is caused by the nvidia driver
I switch to a compute node with nvidia-drive 470 and rtx3090, the seg-fault goes away but a new error came out

```shell
start
Traceback (most recent call last):
  File "basic_example.py", line 5, in <module>
    env = gym.make('OpenCabinetDoor-v0')
  File "/scratch/ray/env/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/scratch/ray/env/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/scratch/ray/env/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/scratch/ray/env/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/scratch/ray/env/anaconda3/envs/mani_skill/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/beegfs/scratch/ray/projects/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 5, in <module>
    from mani_skill.env.base_env import BaseEnv
  File "/mnt/beegfs/scratch/ray/projects/ManiSkill/mani_skill/env/base_env.py", line 59, in <module>
    _renderer = sapien.VulkanRenderer(default_mipmap_levels=1)
RuntimeError: vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed
```

**Comment by fbxiang** [comment]
Have you read the faq at https://github.com/haosulab/ManiSkill/wiki? If not, you should try it first. If so, what is the output of command `vulkaninfo`?

**Comment by ray8828** [comment]
I tried the Q1-Q3 in the wiki, but not helping. Seems our cluster does not have `vulkan` after running `vulkaninfo`, I got:
```shell
Command 'vulkaninfo' not found, but can be installed with:

apt install vulkan-tools
Please ask your administrator.
```
We will install vulkan after ICLR DDL.

btw, installing vulkan is the only way to solve the issue right?

**Comment by fbxiang** [comment]
All you really need is probably just the nvidia.icd file. Vulkan is usually installed with the driver. `vulkaninfo` is a separate program that checks this installation.

**Comment by ray8828** [comment]
I still get
```shell
vk::Instance::enumeratePhysicalDevices: ErrorInitializationFailed
  File "/mnt/beegfs/scratch/ray/projects/ManiSkill/mani_skill/env/base_env.py", line 59, in <module>
    _renderer = sapien.VulkanRenderer(default_mipmap_levels=1)
  File "/mnt/beegfs/scratch/ray/projects/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 5, in <module>
    from mani_skill.env.base_env import BaseEnv
  File "/mnt/beegfs/scratch/ray/projects/ManiSkill/basic_example.py", line 5, in <module>
    env = gym.make('OpenCabinetDoor-v0')
```
when i run the demo script

Our cluster has the `nvidia.icd` file
```shell
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.2.155"
    }
}
```

but after installing vulkaninfo, I got an error when running `vulkaninfo`:
```shell
(base) ray@node-3090-3:/mnt/beegfs/scratch/ray/projects/ManiSkill$ vulkaninfo
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR not set in the environment.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:477: failed with ERROR_INITIALIZATION_FAILED
```

and after i export `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` then i got:
```shell
(base) ray@node-3090-3:/mnt/beegfs/scratch/ray/projects/ManiSkill$ vulkaninfo
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER
```

Any suggestion to solve this problem? Thanks!!

**Comment by ray8828** [comment]
The problem is resolved, it's the issue on our cluster side.

**Comment by ray8828** [comment]
FYI: be careful when using vulkan in slurm cluster multi-gpu node, check the nvidia driver version, some earlier sub-version of 460 driver will lead to bug: the cgroup allocates you a specific GPU, but if it's not the first GPU device, vulkan with early driver version might directly throw an error without going to check later GPU devices that you have access to.

**Comment by Wanwk** [comment]
> FYI: be careful when using vulkan in slurm cluster multi-gpu node, check the nvidia driver version, some earlier sub-version of 460 driver will lead to bug: the cgroup allocates you a specific GPU, but if it's not the first GPU device, vulkan with early driver version might directly throw an error without going to check later GPU devices that you have access to.

Hi! I met the same problem as you. Could you tell me how you solved this problem？

**Comment by Wanwk** [comment]
> The problem is resolved, it's the issue on our cluster side.
Hi! I met the same problem as you. Could you tell me how you solved this problem？ @ray8828

**Comment by Wanwk** [comment]
> FYI: be careful when using vulkan in slurm cluster multi-gpu node, check the nvidia driver version, some earlier sub-version of 460 driver will lead to bug: the cgroup allocates you a specific GPU, but if it's not the first GPU device, vulkan with early driver version might directly throw an error without going to check later GPU devices that you have access to.

Hi! I met the same problem as you. Could you tell me how you solved this problem？ @ray8828
